name: Soutei
version: '2.1'
synopsis: a logic-based trust-management system
description: ! 'SOUTEI is a trust-management system, a dialect of Binder, for access

  control in distributed systems. Soutei policies and credentials are written

  in a declarative logic-based security language and thus constitute

  distributed logic programs. Soutei policies are modular, concise, and

  readable. They support policy verification, and, despite the simplicity of

  the language, express role- and attribute-based access control lists, and

  conditional delegation.

  http://soutei.sourceforge.net/

  http://github.com/mstone/soutei'
author:
- Oleg Kiselyov <oleg@okmij.org>
- Andrew Pimlott <andrew@pimlott.net>
maintainer: Michael Stone <mistone@akamai.com>
license: GPL-2
ghc-options:
- -Wall
- -funbox-strict-fields
dependencies:
- containers
- directory
- mtl
- network
- old-locale
- old-time
- parallel
- parsec
- QuickCheck ==2.*
- random
library:
  ghc-prof-options:
  - -prof
  - -auto-all
  exposed-modules:
  - Soutei.Soutei
  - Soutei.Assertions
  - Soutei.Check
  - Soutei.Client
  - Soutei.FBackTrack
  - Soutei.FBackTrackT
  - Soutei.GBBFS
  - Soutei.GBBFS1
  - Soutei.Lirs
  - Soutei.Logic
  - Soutei.Parsec
  - Soutei.Sexpr
  - Soutei.Syntax
  dependencies:
  - base >=4
executables:
  soutei-cli:
    main: soutei-server.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    ghc-prof-options:
    - -prof
    - -auto-all
    dependencies:
    - base >=4.0
    - Soutei
  soutei-server:
    main: soutei-server.hs
    source-dirs: app
    ghc-options:
    - -rtsopts
    - -threaded
    ghc-prof-options:
    - -prof
    - -auto-all
    dependencies:
    - base >=4.0
    - Soutei
tests:
  soutei-metcast-tests:
    main: demo/metcast-channels/soutei-metcast-tests.hs
    ghc-options:
    - -rtsopts
    - -threaded
    dependencies:
    - base >=4.0
    - Soutei
stability: experimental
